export const expensesTypes = {
  SELECT_EXPENSE: 'SELECT_EXPENSE',
  FILTER_EXPENSES: 'FILTER_EXPENSES',
  TOTAL_EXPENSES: 'TOTAL_EXPENSES',
  ADD_EXPENSE: 'ADD_EXPENSE',
  GET_EXPENSES: 'GET_EXPENSES',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
};
